/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(testdemo)'}/test1` | `/test1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(testdemo)'}/test2` | `/test2`; params?: Router.UnknownInputParams; } | { pathname: `/highLevelGoals/addYourGoal`; params?: Router.UnknownInputParams; } | { pathname: `/highLevelGoals`; params?: Router.UnknownInputParams; } | { pathname: `/medicalCondition/another`; params?: Router.UnknownInputParams; } | { pathname: `/medicalCondition`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(testdemo)'}/test1` | `/test1`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(testdemo)'}/test2` | `/test2`; params?: Router.UnknownOutputParams; } | { pathname: `/highLevelGoals/addYourGoal`; params?: Router.UnknownOutputParams; } | { pathname: `/highLevelGoals`; params?: Router.UnknownOutputParams; } | { pathname: `/medicalCondition/another`; params?: Router.UnknownOutputParams; } | { pathname: `/medicalCondition`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(testdemo)'}/test1${`?${string}` | `#${string}` | ''}` | `/test1${`?${string}` | `#${string}` | ''}` | `${'/(testdemo)'}/test2${`?${string}` | `#${string}` | ''}` | `/test2${`?${string}` | `#${string}` | ''}` | `/highLevelGoals/addYourGoal${`?${string}` | `#${string}` | ''}` | `/highLevelGoals${`?${string}` | `#${string}` | ''}` | `/medicalCondition/another${`?${string}` | `#${string}` | ''}` | `/medicalCondition${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(testdemo)'}/test1` | `/test1`; params?: Router.UnknownInputParams; } | { pathname: `${'/(testdemo)'}/test2` | `/test2`; params?: Router.UnknownInputParams; } | { pathname: `/highLevelGoals/addYourGoal`; params?: Router.UnknownInputParams; } | { pathname: `/highLevelGoals`; params?: Router.UnknownInputParams; } | { pathname: `/medicalCondition/another`; params?: Router.UnknownInputParams; } | { pathname: `/medicalCondition`; params?: Router.UnknownInputParams; };
    }
  }
}
